import './globals.css';
import { ToastContainer } from './compos/Toast';
import 'react-toastify/dist/ReactToastify.css';
export const metadata = {
  title: 'X',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=' overflow-auto p-0 m-0 bg-black' >
        {children}
        <ToastContainer theme='dark' position='bottom-right' />
      </body>
    </html>
  )
}
