import './globals.css';


export const metadata = {
  title: 'X',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=' overflow-auto p-0 m-0' >{children}</body>
    </html>
  )
}
